export const ENDPOINTS = {
    // AUTH
    AUTH:{
        LOGIN: "admin/auth/login",
        REGISTER: "admin/auth/register",
        FORGOT_PASSWORD: "admin/auth/forgot_password",
        RESET_PASSWORD: "admin/auth/reset_password",
        CHANGE_PASSWORD: "admin/auth/change-password",
        OTP: "admin/auth/otp",
        SEND_OTP: "admin/auth/resend_otp",
        VERIFY_OTP: "admin/auth/verify_otp",
    },
    COMMON:{
        UPLOAD_FILE: "user/auth/upload_file",
        COMMON_CONTENT:"common/common_content"
    },
    // PRIVATE
    PRIVATE:{
        CREATE_THEME: "admin/theme/create_theme",
        LIST_THEME:"admin/theme/list_theme",
        DELETE_THEME:"admin/theme/delete_theme",
        CREATE_MODULE: "admin/modules/create_module",
        CREATE_SUB_MODULE:"admin/submodules/create_submodule",
        LIST_MODULE:"admin/modules/list_module",
        UPDATE_COMMON_CONTENT:"admin/common/common_content",
        RESET_COMMON_CONTENT:"admin/common/reset_common_content",
        LIST_SUB_MODULE:"admin/submodules/list_submodule",
        CONTACTUS_LIST:"admin/contactus/list",
        DELETE_CONTACTUS:"admin/contactus/delete",
        CONTACTUS_DETAIL:"admin/contactus/details",
        CONTACTUS_REPLY:"admin/contactus/reply",
        CREATE_PHASE:"admin/phases/create_phase",
        LIST_PHASE:"admin/phases/list_phase",
        CREATE_LESSONS:"admin/exercise/create_exercise_details",
        LIST_LESSONS:"admin/exercise/list_exercise_details",
        THEME_DETAIL:"admin/theme/theme_details",
        UPDATE_THEME:"admin/theme/update_theme",
        DETAIL_MODULE:"admin/modules/module_details",
        DELETE_MODULE:"admin/modules/delete_module",
        UPDATE_MODULE:"admin/modules/update_module",
        SUBMODULE_DETAIL:"admin/submodules/submodule_details",
        SUBMODULE_DELETE:"admin/submodules/delete_submodule",
        SUBMODULE_UPDATE:"admin/submodules/update_submodule",
        PHASE_DELETE:"admin/phases/delete_phase",
        PHASE_DETAIL:"admin/phases/phase_details",
        PHASE_UPDATE:"admin/phases/update_phase",
        LESSON_UPDATE:"admin/exercise/update_exercise_details",
        LESSON_DELETE:"admin/exercise/delete_exercise_details",
        LESSON_DETAIL:"admin/exercise/exercise_details",
        EXERCISE_CREATE:"admin/exercise/create_exercise",
        EXERCISE_UPDATE:"admin/exercise/update_exercise",
        EXERCISE_DELETE:"admin/exercise/delete_exercise",
        EXERCISE_DETAIL:"admin/exercise/single_exercise",
        EXERCISE_LIST:"admin/exercise/list_exercise",
        ADMIN_DETAIL:"admin/auth/details",
        PROFILE_EDIT:"admin/auth/profile",
        CHANGE_PASSWORD:"admin/auth/change_password",
        ADMIN_DASHBOARD:"admin/user/dashboard"

    }
}