services:

    api:
        build: .
        container_name: heal_api
        command : npm run api
        ports: 
        - "3001:3001"
        env_file:
          - .env

    bull-worker:
      build: .
      container_name: bull-worker
      command: npm run bull-worker
      env_file:
        - .env

    excel-worker:
        build: .
        container_name: excel-worker
        command: npm run excel-worker
        env_file:
          - .env

    redis:
      image: redis:7-alpine
      container_name: redis
    