import { NavigationContainer, DefaultTheme } from '@react-navigation/native';
const LightTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    background: '#F4EEE2',
    black: 'black',
    white: 'white',
    brown: '#3A2110',
  },
  images: {
    logo: require('../assets/logo.png'),
    h: require('../assets/h.png'),
    phone: require('../assets/phone.png'),
    start: require('../assets/start.png'),
    stars: require('../assets/stars.png'),
    apple: require('../assets/apple.png'),
    google: require('../assets/google.png'),
    fb: require('../assets/fb.png'),
    group: require('../assets/group.png'),
    tiktok: require('../assets/tiktok.png'),
    youtube: require('../assets/youtube.png'),
    twitter: require('../assets/twitter.png'),
    insta: require('../assets/insta.png'),
    other: require('../assets/other.png'),
    heartRope: require('../assets/heartRope.png'),
    tick: require('../assets/tick.png'),
    family: require('../assets/family.png'),
    friendship: require('../assets/friendship.png'),
    loneliness: require('../assets/loneliness.png'),
    needtotalk: require('../assets/needtotalk.png'),
    romantic: require('../assets/romantic.png'),
    selfconfident: require('../assets/selfconfident.png'),
    door: require('../assets/door.png'),
    lock: require('../assets/lock.png'),
    must: require('../assets/must.png'),
    private: require('../assets/private.png'),
    tickbox: require('../assets/tickbox.png'),
    uncheck: require('../assets/uncheck.png'),
    back: require('../assets/back.png'),
    bird: require('../assets/Bird.gif'),
  },
};

const DarkTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    background: '#F4EEE2',
    black: 'black',
    white: 'white',
    brown: '#3A2110',
  },
  images: {
    logo: require('../assets/logo.png'),
    h: require('../assets/h.png'),
    phone: require('../assets/phone.png'),
    start: require('../assets/start.png'),
    stars: require('../assets/stars.png'),
    apple: require('../assets/apple.png'),
    google: require('../assets/google.png'),
    fb: require('../assets/fb.png'),
    group: require('../assets/group.png'),
    tiktok: require('../assets/tiktok.png'),
    youtube: require('../assets/youtube.png'),
    twitter: require('../assets/twitter.png'),
    insta: require('../assets/insta.png'),
    other: require('../assets/other.png'),
    heartRope: require('../assets/heartRope.png'),
    tick: require('../assets/tick.png'),
    family: require('../assets/family.png'),
    friendship: require('../assets/friendship.png'),
    loneliness: require('../assets/loneliness.png'),
    needtotalk: require('../assets/needtotalk.png'),
    romantic: require('../assets/romantic.png'),
    selfconfident: require('../assets/selfconfident.png'),
    door: require('../assets/door.png'),
    lock: require('../assets/lock.png'),
    must: require('../assets/must.png'),
    private: require('../assets/private.png'),
    tickbox: require('../assets/tickbox.png'),
    uncheck: require('../assets/uncheck.png'),
    back: require('../assets/back.png'),
    bird: require('../assets/Bird.gif'),
  },
};
export { LightTheme, DarkTheme };
