const QUERY_KEYS = {
    USER: "user",
}

const MUTATION_KEYS = {
    OTP: "otp",
    LOGIN: "login",
    LOGOUT: "logout",
    REGISTER: "register",
    SEND_OTP: "send-otp",
    VERIFY_OTP: "verify-otp",
    FORGOT_PASSWORD: "forgot-password",
    RESET_PASSWORD: "reset-password",
    CHANGE_PASSWORD: "change-password",
    UPLOAD_FILE: "upload-file",
    CREATE_THEME: "create-theme",
    LIST_THEME: "list-theme",
    DELETE_THEME: "delete-theme",
    CREATE_MODULE: "create-module",
    LIST_MODULE: "list-module",
    COMMON_CONTENT: "common-content",
    UPDATE_COMMON_CONTENT: "update-common-content",
    RESET_COMMON_CONTENT: "reset-common-content",
    CREATE_SUB_MODULE: "create-sub-module",
    LIST_SUB_MODULE: "list-sub-module",
    CONTACTUS_LIST: "contactus-list",
    DELETE_CONTACTUS: "delete-contactus",
    CONTACTUS_DETAIL: "contactus-detail",
    CONTACTUS_REPLY: "contactus-reply",
    CREATE_PHASE: "create-phase",
    LIST_PHASE: "list-phase",
    CREATE_LESSONS: "create-lessons",
    LIST_LESSONS: "list-lessons",
    THEME_DETAIL: "theme-detail",
    UPDATE_THEME: "update-theme",
    DETAIL_MODULE: "detail-module",
    DELETE_MODULE: "delete-module",
    UPDATE_MODULE: "update-module",
    SUBMODULE_DETAIL: "submodule-detail",
    SUBMODULE_DELETE: "submodule-delete",
    SUBMODULE_UPDATE: "submodule-update",
    PHASE_DELETE: "phase-delete",
    PHASE_DETAIL: "phase-detail",
    PHASE_UPDATE: "phase-update",
    LESSON_DELETE: "lesson-delete",
    LESSON_DETAIL: "lesson-detail",
    LESSON_UPDATE: "lesson-update",
    EXERCISE_CREATE: "exercise-create",
    EXERCISE_UPDATE: "exercise-update",
    EXERCISE_DELETE: "exercise-delete",
    EXERCISE_DETAIL: "exercise-detail",
    EXERCISE_LIST: "exercise-list",
    ADMIN_DETAIL: "admin-detail",
    PROFILE_EDIT: "profile-edit",
    ADMIN_CHANGE_PASSWORD: "admin-change-password",
    ADMIN_DASHBOARD: "admin-dashboard",
    USERS_LIST: "users-list",
    USERS_DETAIL: "users-detail",
    USERS_STATUS: "users-status",
    LIST_EXCEL_IMPORTS: "list-excel-imports",
    EXCEL_IMPORT: "excel-import",
    ADD_AFFILIATION: "add-affirmation",
    LIST_AFFILIATION: "list-affirmation",
    EDIT_AFFILIATION: "edit-affirmation",
    DELETE_AFFILIATION: "delete-affirmation",
    DETAIL_AFFILIATION: "affirmation-detail",
    
    CATEGORY_CREATE: "create-category",
    CATEGORY_LIST: "list-category",
    CATEGORY_DELETE: "delete-category",
    CATEGORY_DETAIL: "category-detail",
    CATEGORY_UPDATE: "update-category",
    HOMETHEME_CREATE: "create-hometheme",
    HOMETHEME_UPDATE: "update-hometheme",
    HOMETHEME_DELETE: "delete-hometheme",
    HOMETHEME_LIST: "list-hometheme",
    HOMETHEME_DETAIL: "hometheme-detail",
}

export { QUERY_KEYS, MUTATION_KEYS }