import { StyleSheet, Platform } from 'react-native';
import { widthPercentageToDP as wp } from 'react-native-responsive-screen';
import AppFonts from '../../../../constants/fonts';
import AppUtils from '../../../../utils/appUtils';

const style = (colors: any) =>
  StyleSheet.create({
    mainContainer: {
      flex: 1,
      paddingHorizontal: 20,
    },
    aboutTitle: {
      fontFamily: AppFonts.reco,
      fontSize: AppUtils.fontSize(32),
      color: colors.brown,
      marginTop: Platform.OS == 'ios' ? -10 : -12,
      includeFontPadding: false,
    },
    aboutSubtitle: {
      fontFamily: AppFonts.regular,
      fontSize: AppUtils.fontSize(16),
      color: colors.brown,
      marginTop: 4,
      marginBottom: 20,
      includeFontPadding: false,
    },
    heroCard: {
      backgroundColor: '#FFD8B5',
      borderRadius: 22,
      padding: 24,
      alignItems: 'center',
      marginBottom: 24,
    },
    heroLogo: {
      width: 184,
      height: 90,
      marginBottom: Platform.OS == 'ios' ? 28 : 24,
    },
    heroTitle: {
      fontFamily: AppFonts.semiBold,
      fontSize: AppUtils.fontSize(16),
      color: colors.brown,
      letterSpacing: 1,
      marginBottom: 12,
      includeFontPadding: false,
    },
    heroSubtitle: {
      fontFamily: AppFonts.regular,
      fontSize: AppUtils.fontSize(14),
      color: colors.brown,
      textAlign: 'center',
      lineHeight: 22,
      includeFontPadding: false,
    },
    sectionTitle: {
      fontFamily: AppFonts.semiBold,
      fontSize: AppUtils.fontSize(16),
      color: colors.brown,
      marginBottom: 12,
      includeFontPadding: false,
    },
    whiteCard: {
      backgroundColor: colors.white,
      borderRadius: 16,
      padding: 12,
      marginBottom: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    missionText: {
      fontFamily: AppFonts.regular,
      fontSize: AppUtils.fontSize(12),
      color: colors.brown,
      lineHeight: 22,
      includeFontPadding: false,
    },
    missionTextMargin: {
      marginTop: 16,
    },
    gridContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    valueCard: {
      backgroundColor: colors.white,
      borderRadius: 16,
      padding: 16,
      width: '48%',
      marginBottom: 16,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    valueIconContainer: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: 'rgba(234,172,144,0.17)',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 12,
    },
    valueIcon: {
      width: 56,
      height: 56,
      marginBottom: 10,
    },
    valueTitle: {
      fontFamily: AppFonts.semiBold,
      fontSize: AppUtils.fontSize(14),
      color: colors.brown,
      textAlign: 'center',
      marginBottom: 8,
      includeFontPadding: false,
    },
    valueDesc: {
      fontFamily: AppFonts.regular,
      fontSize: AppUtils.fontSize(12),
      color: colors.brown,
      textAlign: 'center',
      lineHeight: 18,
      includeFontPadding: false,
    },
    importantCard: {
      backgroundColor: 'rgba(252,242,241)',
      borderRadius: 16,
      padding: 12,
      marginBottom: 24,
    },
    importantTitle: {
      fontFamily: AppFonts.medium,
      fontSize: AppUtils.fontSize(16),
      color: colors.brown,
      marginBottom: 16,
      includeFontPadding: false,
    },
    bulletItem: {
      flexDirection: 'row',
      marginBottom: 12,
    },
    bulletText: {
      fontFamily: AppFonts.regular,
      fontSize: AppUtils.fontSize(14),
      color: colors.brown,
      lineHeight: 24,
      flex: 1,
      includeFontPadding: false,
    },
    separator: {
      height: 1,
      backgroundColor: colors.brown,
      opacity: 0.3,
      marginBottom: 12,
    },
    footerTextImportant: {
      fontFamily: AppFonts.regular,
      fontSize: AppUtils.fontSize(13),
      color: colors.brown,
      lineHeight: 20,
      opacity: 0.6,
      includeFontPadding: false,
    },
    linkCard: {
      backgroundColor: 'rgba(249,172,144,0.2)',
      borderRadius: 16,
      padding: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    linkText: {
      fontFamily: AppFonts.medium,
      fontSize: AppUtils.fontSize(14),
      color: colors.brown,
      includeFontPadding: false,
    },
    linkIcon: {
      width: 18,
      height: 18,
      tintColor: colors.brown,
      opacity: 0.7,
    },
    footerContainer: {
      alignItems: 'center',
      paddingVertical: 32,
    },
    versionText: {
      fontFamily: AppFonts.regular,
      fontSize: AppUtils.fontSize(14),
      color: colors.brown,
      marginBottom: 8,
      includeFontPadding: false,
    },
    copyrightText: {
      fontFamily: AppFonts.regular,
      fontSize: AppUtils.fontSize(12),
      color: colors.brown,
      opacity: 0.7,
      marginBottom: 8,
      includeFontPadding: false,
      textAlign: 'center',
    },
    madeWithText: {
      fontFamily: AppFonts.regular,
      fontSize: AppUtils.fontSize(12),
      color: colors.brown,
      opacity: 0.7,
      includeFontPadding: false,
      textAlign: 'center',
    },
    creditsBtn: {
      width: '100%',
      backgroundColor: colors.brown,
      borderRadius: 100,
      marginTop: 20,
      marginBottom: 40,
    },
  });

export default style;
