export const endpoints = {
  register: '/user/auth/register',
  verifyOtp: '/user/auth/verify_otp',
  resendOtp: '/user/auth/resend_otp',
  forgot_password: '/user/auth/forgot_password',
  reset_password: '/user/auth/reset_password',
  login: '/user/auth/login',
  social_login: '/user/auth/social_login',
  update_profile: '/user/auth/profile',
  user_details: '/user/auth/details',
  change_password: '/user/auth/change_password',
  refresh_token: '/user/auth/refresh_token',
  upload_file: '/user/auth/upload_file',
  common_content: '/common/common_content',
};
