const AppRoutes = {
  AuthStack: 'AuthStack',
  NonAuthStack: 'NonAuthStack',
  Splash: 'Splash',
  Welcome: 'Welcome',
  Home: 'Home',
  GetStarted: 'GetStarted',
  HearAboutUs: 'HearAboutUs',
  BringYouHere: 'BringYouHere',
  FeelingsLately: 'FeelingsLately',
  FeelMore: 'FeelMore',
  TimeCommitment: 'TimeCommitment',
  ReadyToStart: 'ReadyToStart',
  RightPlace: 'RightPlace',
  PrivacyMatters: 'PrivacyMatters',
  Terms: 'Terms',
  PrivacyPolicy: 'PrivacyPolicy',
  Warning: 'Warning',
  CreatingSpace: 'CreatingSpace',
  AccessScreen: 'AccessScreen',
  SignIn: 'SignIn',
  SignUp: 'SignUp',
  Verification: 'Verification',
  ForgotPassword: 'ForgotPassword',
  ResetPassword: 'ResetPassword',
  Offer: 'Offer',
  SelectLanguage: 'SelectLanguage',
  Reminder: 'Reminder',
  Premium: 'Premium',
  BottomTab: 'BottomTab',
  Challenges: 'Challenges',
  Modules: 'Modules',
  Journal: 'Journal',
  Settings: 'Settings',
  DailyStreak: 'DailyStreak',
  ProgressTracker: 'ProgressTracker',
  DailyQuote: 'DailyQuote',
  ThemeMixes: 'ThemeMixes',
  ThemeSeeAll: 'ThemeSeeAll',
  ThemeDetail: 'ThemeDetail',
  HealyChat: 'HealyChat',
};

export default AppRoutes;
