const AppRoutes = {
  AuthStack: 'AuthStack',
  NonAuthStack: 'NonAuthStack',
  Splash: 'Splash',
  Welcome: 'Welcome',
  Home: 'Home',
  GetStarted: 'GetStarted',
  HearAboutUs: 'HearAboutUs',
  BringYouHere: 'BringYouHere',
  FeelingsLately: 'FeelingsLately',
  FeelMore: 'FeelMore',
  TimeCommitment: 'TimeCommitment',
  ReadyToStart: 'ReadyToStart',
  RightPlace: 'RightPlace',
  PrivacyMatters: 'PrivacyMatters',
  Terms: 'Terms',
  PrivacyPolicy: 'PrivacyPolicy',
  Warning: 'Warning',
  CreatingSpace: 'CreatingSpace',
  AccessScreen: 'AccessScreen',
  SignIn: 'SignIn',
  SignUp: 'SignUp',
  Verification: 'Verification',
  ForgotPassword: 'ForgotPassword',
  ResetPassword: 'ResetPassword',
  Offer: 'Offer',
  SelectLanguage: 'SelectLanguage',
  Reminder: 'Reminder',
  Premium: 'Premium',
};

export default AppRoutes;
